/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

#include <stdio.h>
struct pair{
	int divisors;
	int occourances;
};
int main(){
	int tri;
	int totalDivisors;
	int toDivide;
	struct pair primeDivisors[50];
	
	for(int i=2;;i++){
		tri = i*(i+1)/2;
		toDivide = tri;
		for(int j=1;;j++){
			if(!(toDivide%j)){
				toDivide/=j
				totalDivisors++;
			}
		}
		if(totalDivisors>400){
			printf("%d %d %d\n",i,tri,totalDivisors);
			return 0;
		}
	}
}
